### ISSUE TITLE
Does ccnet-server need to listen under 0.0.0.0:10001?

### ISSUE THREAD

**Issue by cannotcodetm** [haiwen/ccnet-server#47]
Hello,

I'm about to secure mine seafile server and the only missing part I have got left is how to make ccnet-server just listenting under 127.0.0.1. Is this even possible to do so or is this server needed to listen public with port 10001 and what is this service even doing since I'm not really able to secure it.

Just a reminder of the view of an open-source user:
It isn't really easy to use seafile because of major lack of documentation and non working functions. Therefore seafile is not really following linux filesystem standard etc. There is reallly a lot to improve... but software seems to be nice.

Sincerly,

**Comment by Josue-T** [comment]
Hello, trying to upgrade the yunohost package to the version 7.1 and I detect that ccnet are not able to start if this port is not available. I didn't encounter this issue with 7.0. Maybe are there any regression ?

**Comment by cannotcodetm** [comment]
No response from repo owner. -> Closed.
